import { lazy } from 'react'
import type { ComponentType, LazyExoticComponent } from 'react'

// Lesson component registry: lesson id -> lazily loaded page.
// Every lesson flagged `authored: true` in src/curriculum.ts MUST have an entry here.
export const lessonComponents: Record<string, LazyExoticComponent<ComponentType>> = {
  // Phase 0 — Orientation
  '0.1.1': lazy(() => import('./phase-0/module-01/01-windows-de-workstation')),
  '0.1.2': lazy(() => import('./phase-0/module-01/02-git-and-github')),
  '0.1.3': lazy(() => import('./phase-0/module-01/03-how-this-curriculum-works')),
  // Phase 1 — Python & SQL Foundations
  '1.1.1': lazy(() => import('./phase-1/module-01/01-values-types-variables')),
  '1.1.2': lazy(() => import('./phase-1/module-01/02-collections')),
  '1.1.3': lazy(() => import('./phase-1/module-01/03-control-flow-functions')),
  '1.1.4': lazy(() => import('./phase-1/module-01/04-comprehensions-generators')),
  '1.1.5': lazy(() => import('./phase-1/module-01/05-errors-debugging')),
  '1.2.1': lazy(() => import('./phase-1/module-02/01-projects-venvs-uv')),
  '1.2.2': lazy(() => import('./phase-1/module-02/02-modules-packages-imports')),
  '1.2.3': lazy(() => import('./phase-1/module-02/03-errors-context-managers')),
  '1.2.4': lazy(() => import('./phase-1/module-02/04-type-hints-dataclasses')),
  '1.2.5': lazy(() => import('./phase-1/module-02/05-testing-pytest')),
  '1.2.6': lazy(() => import('./phase-1/module-02/06-logging-not-print')),
  '1.3.1': lazy(() => import('./phase-1/module-03/01-files-csv-encodings')),
  '1.3.2': lazy(() => import('./phase-1/module-03/02-json-nested-data')),
  '1.3.3': lazy(() => import('./phase-1/module-03/03-http-apis-requests')),
  '1.3.4': lazy(() => import('./phase-1/module-03/04-dates-times-timezones')),
  '1.3.5': lazy(() => import('./phase-1/module-03/05-pandas-polars-plain')),
  '1.4.1': lazy(() => import('./phase-1/module-04/01-meet-duckdb')),
  '1.4.2': lazy(() => import('./phase-1/module-04/02-filtering-sorting-expressions')),
  '1.4.3': lazy(() => import('./phase-1/module-04/03-aggregation-group-by')),
  '1.4.4': lazy(() => import('./phase-1/module-04/04-joins-null-semantics')),
  '1.4.5': lazy(() => import('./phase-1/module-04/05-subqueries-case')),
  '1.5.1': lazy(() => import('./phase-1/module-05/01-ctes-query-structure')),
  '1.5.2': lazy(() => import('./phase-1/module-05/02-window-functions-ranking')),
  '1.5.3': lazy(() => import('./phase-1/module-05/03-window-frames-rolling')),
  '1.5.4': lazy(() => import('./phase-1/module-05/04-set-operations-pivots')),
  '1.5.5': lazy(() => import('./phase-1/module-05/05-sql-style-readability')),
  '1.6.1': lazy(() => import('./phase-1/module-06/01-powershell-essentials')),
  '1.6.2': lazy(() => import('./phase-1/module-06/02-env-vars-config')),
  '1.6.3': lazy(() => import('./phase-1/module-06/03-cli-argparse')),
  '1.6.4': lazy(() => import('./phase-1/module-06/04-scheduling')),
  // Phase 2 — Databases, Modeling & File Formats
  '2.1.1': lazy(() => import('./phase-2/module-01/01-postgres-in-docker')),
  '2.1.2': lazy(() => import('./phase-2/module-01/02-ddl-constraints-types')),
  '2.1.3': lazy(() => import('./phase-2/module-01/03-transactions-acid')),
  '2.1.4': lazy(() => import('./phase-2/module-01/04-isolation-mvcc')),
  '2.2.1': lazy(() => import('./phase-2/module-02/01-btrees')),
  '2.2.2': lazy(() => import('./phase-2/module-02/02-explain-analyze')),
  '2.2.3': lazy(() => import('./phase-2/module-02/03-index-design')),
  '2.2.4': lazy(() => import('./phase-2/module-02/04-when-indexes-hurt')),
  '2.3.1': lazy(() => import('./phase-2/module-03/01-workloads')),
  '2.3.2': lazy(() => import('./phase-2/module-03/02-columnar-mechanics')),
  '2.3.3': lazy(() => import('./phase-2/module-03/03-compression-encodings')),
  '2.3.4': lazy(() => import('./phase-2/module-03/04-vectorized-execution')),
  '2.4.1': lazy(() => import('./phase-2/module-04/01-why-model-kimball')),
  '2.4.2': lazy(() => import('./phase-2/module-04/02-facts-dimensions')),
  '2.4.3': lazy(() => import('./phase-2/module-04/03-scd')),
  '2.4.4': lazy(() => import('./phase-2/module-04/04-star-snowflake-obt')),
  '2.5.1': lazy(() => import('./phase-2/module-05/01-format-shootout')),
  '2.5.2': lazy(() => import('./phase-2/module-05/02-parquet-internals')),
  '2.5.3': lazy(() => import('./phase-2/module-05/03-partitioning-small-files')),
  // Phase 3 — Pipelines, Orchestration & the Data Lake
  '3.1.1': lazy(() => import('./phase-3/module-01/01-images-containers-layers')),
  '3.1.2': lazy(() => import('./phase-3/module-01/02-writing-dockerfiles')),
  '3.1.3': lazy(() => import('./phase-3/module-01/03-compose-networks-volumes-healthchecks')),
}
